[package]
name = "aptos-dap"
version = "0.1.0"
description = "Debug Adapter Protocol server for replaying Move transactions"
license = "Apache-2.0"
publish = false
edition = "2024"

[profile.dist]
inherits = "release"
opt-level = "z"
lto = "thin"
strip = true

[dependencies]
anyhow = "1.0.98"
aptos-framework = { git = "https://github.com/aptos-labs/aptos-core.git", branch = "debug-value-extracted" }
aptos-gas-schedule = { git = "https://github.com/aptos-labs/aptos-core.git", branch = "debug-value-extracted" }
aptos-move-cli = { git = "https://github.com/aptos-labs/aptos-core.git", branch = "debug-value-extracted", features = ["testing", "debugger"] }
aptos-move-debugger = { git = "https://github.com/aptos-labs/aptos-core.git", branch = "debug-value-extracted" }
aptos-resource-viewer = { git = "https://github.com/aptos-labs/aptos-core.git", branch = "debug-value-extracted" }
aptos-rest-client = { git = "https://github.com/aptos-labs/aptos-core.git", branch = "debug-value-extracted" }
aptos-types = { git = "https://github.com/aptos-labs/aptos-core.git", branch = "debug-value-extracted" }
aptos-validator-interface = { git = "https://github.com/aptos-labs/aptos-core.git", branch = "debug-value-extracted" }
aptos-vm-environment = { git = "https://github.com/aptos-labs/aptos-core.git", branch = "debug-value-extracted" }
clap = { version = "4.3.9", features = ["derive"] }
crossbeam-channel = "0.5.4"
dap = "0.4.1-alpha1"
hex = "0.4.3"
legacy-move-compiler = { git = "https://github.com/aptos-labs/aptos-core.git", branch = "debug-value-extracted" }
move-binary-format = { git = "https://github.com/aptos-labs/aptos-core.git", branch = "debug-value-extracted" }
move-bytecode-utils = { git = "https://github.com/aptos-labs/aptos-core.git", branch = "debug-value-extracted" }
move-core-types = { git = "https://github.com/aptos-labs/aptos-core.git", branch = "debug-value-extracted" }
move-model = { git = "https://github.com/aptos-labs/aptos-core.git", branch = "debug-value-extracted" }
move-package = { git = "https://github.com/aptos-labs/aptos-core.git", branch = "debug-value-extracted" }
move-resource-viewer = { git = "https://github.com/aptos-labs/aptos-core.git", branch = "debug-value-extracted" }
move-unit-test = { git = "https://github.com/aptos-labs/aptos-core.git", branch = "debug-value-extracted", features = ["debugger"] }
move-vm-runtime = { git = "https://github.com/aptos-labs/aptos-core.git", branch = "debug-value-extracted", features = ["debugger"] }
move-vm-types = { git = "https://github.com/aptos-labs/aptos-core.git", branch = "debug-value-extracted", features = ["debugger"] }
serde_json = "1.0.81"
tokio = { version = "1.35.1", features = ["full"] }
url = "2.4.0"

[dev-dependencies]
expect-test = "1.4.1"
indexmap = "2.7.0"
move-vm-types = { git = "https://github.com/aptos-labs/aptos-core.git", branch = "debug-value-extracted", features = ["testing"] }
regex = "1.9.3"
tempfile = "3.3.0"
triomphe = "0.1.14"

[patch.crates-io]
dudect-bencher = { git = "https://github.com/aptos-labs/dudect-bencher", rev = "9515677c83c58884c1a8c764251753269d46fc0e" }
serde-reflection = { git = "https://github.com/aptos-labs/serde-reflection", rev = "9d2374af843a4562a194529b3cadb8518d7fcd65" }
merlin = { git = "https://github.com/aptos-labs/merlin" }
ark-ec = { git = "https://github.com/aptos-labs/algebra", branch = "fix-fft-parallelism-cutoff" }
ark-ff = { git = "https://github.com/aptos-labs/algebra", branch = "fix-fft-parallelism-cutoff" }
ark-ff-macros = { git = "https://github.com/aptos-labs/algebra", branch = "fix-fft-parallelism-cutoff" }
ark-ff-asm = { git = "https://github.com/aptos-labs/algebra", branch = "fix-fft-parallelism-cutoff" }
ark-poly = { git = "https://github.com/aptos-labs/algebra", branch = "fix-fft-parallelism-cutoff" }
ark-serialize = { git = "https://github.com/aptos-labs/algebra", branch = "fix-fft-parallelism-cutoff" }

# Uncomment the section below to use local aptos-core dependencies
#[patch."https://github.com/aptos-labs/aptos-core.git"]
#aptos-framework = { path = "../aptos-core/aptos-move/framework" }
#aptos-gas-schedule = { path = "../aptos-core/aptos-move/aptos-gas-schedule" }
#aptos-move-cli = { path = "../aptos-core/aptos-move/cli" }
#aptos-move-debugger = { path = "../aptos-core/aptos-move/aptos-debugger" }
#aptos-resource-viewer = { path = "../aptos-core/aptos-move/aptos-resource-viewer" }
#aptos-rest-client = { path = "../aptos-core/crates/aptos-rest-client" }
#aptos-types = { path = "../aptos-core/types" }
#aptos-validator-interface = { path = "../aptos-core/aptos-move/aptos-validator-interface" }
#aptos-vm-environment = { path = "../aptos-core/aptos-move/aptos-vm-environment" }
#legacy-move-compiler = { path = "../aptos-core/third_party/move/move-compiler-v2/legacy-move-compiler" }
#move-binary-format = { path = "../aptos-core/third_party/move/move-binary-format" }
#move-bytecode-utils = { path = "../aptos-core/third_party/move/tools/move-bytecode-utils" }
#move-core-types = { path = "../aptos-core/third_party/move/move-core/types" }
#move-model = { path = "../aptos-core/third_party/move/move-model" }
#move-package = { path = "../aptos-core/third_party/move/tools/move-package" }
#move-resource-viewer = { path = "../aptos-core/third_party/move/tools/move-resource-viewer" }
#move-unit-test = { path = "../aptos-core/third_party/move/tools/move-unit-test" }
#move-vm-runtime = { path = "../aptos-core/third_party/move/move-vm/runtime" }
#move-vm-types = { path = "../aptos-core/third_party/move/move-vm/types" }