[package]
name = "move-vm-debug"
version = "0.1.0"
description = "Debug value serialization for the Move VM"
license = "Apache-2.0"
publish = false
edition = "2024"

[dependencies]
move-binary-format = { path = "../../../aptos-core/third_party/move/move-binary-format" }
move-core-types = { path = "../../../aptos-core/third_party/move/move-core/types" }
move-vm-types = { path = "../../../aptos-core/third_party/move/move-vm/types" }

[dev-dependencies]
move-vm-types = { path = "../../../aptos-core/third_party/move/move-vm/types", features = ["testing"] }
triomphe = "0.1.14"
