[package]
name = "move-vm-debugger"
version = "0.1.0"
description = "Channel-based DAP debug loop for the Move VM"
license = "Apache-2.0"
publish = false
edition = "2024"

[dependencies]
crossbeam-channel = "0.5.4"
move-binary-format = { path = "../../../aptos-core/third_party/move/move-binary-format" }
move-core-types = { path = "../../../aptos-core/third_party/move/move-core/types" }
move-vm-debug = { path = "../move-vm-debug" }
move-vm-runtime = { path = "../../../aptos-core/third_party/move/move-vm/runtime" }
move-vm-types = { path = "../../../aptos-core/third_party/move/move-vm/types" }
