[package]
name = "move-vm-debugger"
version = "0.1.0"
description = "Channel-based DAP debug loop for the Move VM"
license = "Apache-2.0"
publish = false
edition = "2024"

[dependencies]
crossbeam-channel = { workspace = true }
move-binary-format = { workspace = true }
move-core-types = { workspace = true }
move-vm-runtime = { workspace = true, features = ["debugger"] }
move-vm-types = { workspace = true }

[dev-dependencies]
move-vm-types = { workspace = true, features = ["testing"] }
triomphe = "0.1.14"